import type { Course } from '@/interfaces/course'
import {string} from "prop-types";

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/program_1.jpeg',
    title: 'Corporate Governance',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 2,
    cover: '/program_2.png',
    title: 'UI/UX Complete Guide',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
    description: "",
  },
  {
    id: 3,
    cover: '/program_3.png',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
    description: "",
  },
  {
    id: 4,
    cover: '/program_4.png',
    title: 'Certified Board Member',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
    description: "",
  },
  {
    id: 5,
    cover: '/program_5.png',
    title: 'Business Sustainability Management',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
    description: "",
  },
  {
    id: 6,
    cover: '/program_6.png',
    title: 'Ethical Hacking Bootcamp Zero to Mastery',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
    description: "",
  },
  {
    id: 7,
    cover: '/program_7.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 8,
    cover: '/program_8.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 9,
    cover: '/program_9.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 10,
    cover: '/program_10.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 11,
    cover: '/program_11.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
  {
    id: 12,
    cover: '/program_12.png',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    description: "",
  },
]